# Generated by Django 3.1.1 on 2020-09-08 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentapplication',
            old_name='owner',
            new_name='hirer',
        ),
    ]
