# Generated by Django 3.0.3 on 2020-09-07 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('UNA', 'Unapproved'), ('ACC', 'Accepted'), ('REJ', 'Rejected')], default='UNA', max_length=3)),
                ('comments', models.TextField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_applications', to='equipment.Equipment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_applications', to='user.User')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
