# Generated by Django 3.0.3 on 2020-09-07 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('UNR', 'Unreleased'), ('UNA', 'Unapproved'), ('AVA', 'Available'), ('REN', 'Rented'), ('RET', 'Returned')], default='UNR', max_length=3)),
                ('lease_term_begin', models.DateTimeField()),
                ('lease_term_end', models.DateTimeField()),
                ('user_comments', models.TextField()),
                ('current_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_equipments', to='user.User')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_equipments', to='user.User')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
