# Generated by Django 3.0.3 on 2020-09-09 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('1[345678]\\d{9}', message='Please Enter the right phone number!')]),
        ),
    ]
