# Generated by Django 3.1.1 on 2020-09-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20200908_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='lease_term_begin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='lease_term_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='user_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
