# Generated by Django 3.0.3 on 2020-09-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200908_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
